config/routes.rb
Mrx::Application.routes.draw do
  root :to => 'home#index'

  get "home/index"
  post '/contato' => 'home#contact', as: :contact
end

app/models/mailer.rb
class Mailer
  include ActiveModel::Validations
  include ActiveModel::Conversion

  attr_accessor :name, :email, :phone, :title, :message

  validates :name, :email, :phone, :message, presence: :true

  def initialize attributes={}
    self.name = attributes[:name]
    self.email = attributes[:email]
    self.title = attributes[:title]
    self.phone = attributes[:phone]
    self.message = attributes[:message]
  end

  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def contact
    @mailer = Mailer.new params[:contact]

    if @mailer.valid?
      ContactMailer.send_contact(@mailer).deliver
      render text: 'ok'
    else
      render status: 412, text: 'error'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_contato.html.erb
<div id="contato" class="grid_17 push_3">
	<h1 class="grid_3 omega">Contato</h1>

	<section class="grid_12">
		<h1>Informações</h1>

		<ul class="grid_5 alpha">
			<li class="black">E-mail.</li>
			<a href="#">contato@mrxempresarial.com.br</a>
		</ul>

		<ul class="grid_6">
			<li class="black">Facebook.</li>
			<a href="http://www.facebook.com">facebook.com/mrxempresarial</a>
		</ul>

		<ul class="grid_5 alpha">
			<li class="black">Twitter.</li>
			<a href="http://www.twitter.com">@mrx_empresarial</a>
		</ul>
	</section>

	<section class="titulo2 grid_12 push_3 alpha">
  <h1>Formulário</h1>
  <div class="modal hide">
    <h2>Modal</h2>
    <h3>Modal</h3>
  </div>

		<%= form_for(Mailer.new, url: contact_path) do |form| %>
			<div class="grid_5 alpha">
				<p>Nome.</p>
				<%= text_field_tag 'contact[name]', nil %>

				<p>Telefone.</p>
				<%= text_field_tag 'contact[phone]', nil %>

				<p>E-mail.</p>
				<%= email_field_tag 'contact[email]', nil %>
			</div>

			<div class="grid_5">
				<p>Título.</p>
				<%= text_field_tag 'contact[title]', nil, value: '' %>

				<p>Mensagem.</p>
				<%= text_area_tag 'contact[message]', nil %>
			</div>

			<div class="grid_1">
				<%= submit_tag 'Enviar', :disable_with => 'Enviando...' %>
			</div>
    <% end %>
	</section>
</div>	

app/views/home/_mod_negocio.html.erb
<div id="mod_negocio" class="grid_17 push_3">
	<h1 class="grid_3 omega">Modelo de Negócio</h1>

	<section class="grid_12">
		<h1>Segmento de Clientes</h1>

		<ul>
			<li class="grid_5 alpha">Grupos de Investidores</li>
			<li class="grid_6">Pessoas físicas aspirantes a empreededores</li>
			<li class="grid_5 alpha">Investidores individuais</li>
			<li  class="grid_6">Cadeia de Varejo</li>
		</ul>
	</section>

	<section class="titulo2 grid_12 push_3 alpha">
		<h1>Proposta de Valor</h1>

		<ul>
			<li class="grid_5 alpha">Novidade</li>
			<li class="grid_6">Personalização</li>
			<li class="grid_5 alpha">Desempenho</li>
		</ul>
	</section>

	<section class="titulo2 grid_12 push_3 alpha">
		<h1>Canais</h1>

		<ul>
			<li class="grid_5 alpha">Particulares</li>
			<li class="grid_6">Parcerias</li>
		</ul>
	</section>

	<section class="titulo2 grid_12 push_3 alpha">
		<h1>Relacionamento Com o Cliente</h1>

		<ul>
			<li>Pessoais (assistência pessoal dedicada)</li>
			<li>Automatizados (website com armazenamento de informações)</li>
		</ul>
	</section>

	<section class="titulo2 grid_12 push_3 alpha">
		<h1>Fontes de Receita</h1>

		<ul>
			<li>Transações de renda resultantes de produto entregue (on demand)</li>
			<li>Renda recorrente</li>
			<li>Headcount ou locação de mão de obra / recursos</li>
			
			<p>A precificação é variável (dinâmica), mudam com base nas condições de mercado.</p>
		</ul>
	</section>

	<section class="titulo2 grid_12 push_3 alpha">
		<h1>Recursos Principais</h1>

		<ul>
			<li>Fisicos</li>
			<li class="inside">- Necessário definir local (de preferência otimizado), e mobiliário necessário</li>
			<br>

			<li>Financeiros</li>
			<li class="inside">- Definir o fluxo de caixa e estabelecer o ponto de equilíbrio. Alinhar os valores tratados na Offer  Letter</li>
			<br>

			<li>Intelectuais</li>
			<li class="inside">- Experiências pessoais dos sócios, banco de dados</li>
			<br>

			<li>Humanos</li>
			<li class="inside">- Definir os recursos, seus jobs descriptions e os valores disponíveis para alocação</li>
		</ul>
	</section>

	<section class="titulo2 grid_12 push_3 alpha">
		<h1>Atividades-Chave</h1>

		<ul>
			<li class="grid_5 alpha">Resolução de Problemas</li>
			<li class="grid_6">Estabilização de operações</li>
		</ul>
	</section>

	<section class="titulo2 grid_12 push_3 alpha">
		<h1>Parcerias Principais</h1>

		<ul>
			<li class="grid_5 alpha">Consultoria</li>
			<li class="grid_6">Investidores principais</li>
		</ul>
	</section>

	<section class="titulo2 grid_12 push_3 alpha">
		<h1>Estrutura de Custos</h1>

		<ul>
			<li class="grid_5 alpha">Business Plan (foco financeiro)</li>
			<li class="grid_6">Receitas variáveis</li>
			<li class="grid_5 alpha">Receitas recorrentes (fixo)</li>
		</ul>
	</section>
	
	<section class="titulo2 grid_12 push_3 alpha">
		<h1>O Quadro - Modelo de Negócio</h1>

		<img src="/assets/tabela_mod_neg.png" alt="Modelo de Negocio">
	</section>		
</div>

app/views/home/_servicos.html.erb
<div id="servicos" class="grid_17 push_3">
	<h1 class="grid_3 omega">Serviços</h1>

	<section class="grid_12">
		<h1>Suporte Operacional</h1>

		<ul>
			<li class="grid_5 alpha">Identificação do negócio</li>
			<li class="grid_7 omega">Estruturação da empresa</li>
			<li class="grid_5 alpha">Business planning</li>
			<li class="grid_7 omega ">Escolha de ponto comercial</li>
		</ul>
	</section>

	<section class="titulo2 grid_12 push_3 alpha">
		<h1>Gestão Operacional</h1>

		<ul class="grid_5 alpha">
			<li>Gestão (compartilhada)</li>

			<li class="inside">- Operacional</li>
			<li class="inside">- Suprimentos</li>
			<li class="inside">- Recursos Humanos</li>
			<li class="inside">- Treinamento Operacional</li>
			<li class="inside">- Coaching de seus membros</li>
			<br>
			<li>Gestão (quarteirizada)</li>
			<li class="inside">- Contábil</li>
			<li class="inside">- Fiscal</li>
		</ul>

		<ul class="grid_5">
			<li>Assessoria (quarteirizada)</li>

			<li class="inside">- Engenharia</li>
			<li class="inside">- TI</li>
			<li class="inside">- Jurídica</li>
		</ul>
	</section>

	<section class="titulo2 grid_12 push_3 alpha">
		<h1>Gestão Estratégica</h1>

		<ul>
			<li class="grid_6">Estudo para aumento de capital</li>
			<li class="grid_5">Engenharia Financeira</li>
			<li class="grid_6">Reposicionamento de marca no mercado</li>
		</ul>
	</section>		
</div>

app/views/home/_sobre_nos.html.erb
<div id="sobre_nos" class="grid_14 push_3">
	<h1 class='grid_3 omega'>Sobre Nós</h1>

	<img class="grid_9 pull_3" src="/assets/tabuleiro.png" alt="Imagem">

	<section id="objetivo" class="grid_5 push_10 alpha">
		<h1>Objetivo</h1>
		<p>
			A MRX é especializada na identificação de oportunidades de negócio compatíveis com aspirantes empreendedores e na formação de grupos de investidores ou investidores individuais.
		</p>
	</section>

	<section class="titulo2 grid_12 push_3 alpha">
		<h1>Equipe</h1>
		
		<h2>Marcelo Real</h2>
		<p>Graduado em Administração de Empresas pela FEI-SP e Pós-Graduado em Gestão Financeira pela FGV-SP.</p>
		<p>20 anos de experiência nas áreas de Real State, Infraestrutura, Serviços, Terceirizações e Quarteirizações, facilidades, Franchising e Varejo.</p>

		<h2>Adriana Ruta Real</h2>
		<p>Graduada em Letras (Tradução e Interpretação – Inglês e Português) pela Universidade Anhembi Morumbi/SP.</p>
		<p>Secretária Executiva Bilíngue com 20 anos de experiência em empresas multinacionais como Visa, PepsiCo e Kraft Foods.</p>

	</section>
</div>

app/views/home/index.html.erb
<div class="container_20">
  <header class="grid_15 push_3">
    <%= image_tag "logo.png", alt: 'MRX Empresarial' %>

    <ul class="menu">
      <li class="selected grid_2 alpha">
        <%=link_to "Sobre Nós", "#sobre_nos" %>
      </li>
      <li class="grid_2">
        <%=link_to "Serviços", "#servicos" %>
      </li>
      <li class="links_line2 grid_3">
        <%=link_to "Modelo de Negócio", "#mod_negocio" %>
      </li>
      <li class="grid_2 omega">
        <%=link_to "Contato", "#contato"%>
      </li>
    </ul>
  </header>
</div>
<div id="slider-menu">
  <div class="container_20">
    <div class="grid_15 push_3">
      <%= image_tag "logo.png", alt: 'MRX Empresarial', class: 'grid_2 alpha' %>

      <ul class="menu grid_12 push_1 omega">
        <li class="selected grid_2 alpha">
          <%=link_to "Sobre Nós", "#sobre_nos" %>
        </li>
        <li class="grid_2">
          <%=link_to "Serviços", "#servicos" %>
        </li>
        <li class="links_line2 grid_3">
          <%=link_to "Modelo de Negócio", "#mod_negocio" %>
        </li>
        <li class="grid_2 omega">
          <%=link_to "Contato", "#contato"%>
        </li>
      </ul>
    </div>
  </div>
</div>

<div id="content" class="container_20">
  <%= render 'sobre_nos' %>
  <%= render 'servicos' %>
  <%= render 'mod_negocio' %>
  <%= render 'contato' %>
</div>

<div class="footer-wrapper">
  <div class="container_20">
    <p>© 2013 MRX Empresarial  |  Todos os Direitos Reservados<br>Desenvolvido por <a href="http://www.loldesign.com.br">LolDesign</a></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
      <meta charset="UTF-8">

	  <title>MRX</title>

        <!--[if lt IE 9]>
            <script type="text/javascript" src="script/html5.js"></script>
        <![endif]-->

	  	<%= stylesheet_link_tag    "application", :media => "all" %>
	  	<%= javascript_include_tag "application" %>
	    <%= csrf_meta_tags %>
	</head>
	<body>

	<%= yield %>

	</body>
</html>